### PR TITLE
feat: add support for volume encryption

### LINKED ISSUE #1796: Add support for disks using encrypted storage policies
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Currently, if you specify an encrypted storage policy for a disk subresource (where the disk already exists) when creating a VM in vsphere, you hit an error.

This is because vsphere does not support encrypting a disk on attachment to a new VM with an encrypted storage policy. 

Vsphere does support a two step process - attaching disks to a VM which has an encrypted storage policy, and then changing the disks to have an encrypted storage policy.

Terraform-provider-vsphere could handle creating a VM, with disk subresources which have encrypted storage policies by using this two step process - creating the VM with its storage policy and attaching the disks with the default storage policy, and as a post-creation step, setting the disk storage policy to the encrypted storage policy specified.

It should also handle attaching already-encrypted disks to a new VM which has an encrypted storage policy. I don't quite know how to do this yet.

A trickier scenario for terraform-provider-vsphere to handle would be creating a VM with an unencrypted storage policy and attaching encrypted disks to this as unencrypted subresource disks. This would require something like: creating an encrypted VM with the disks attached as encrypted subresource disks, and then changing all storage policies to unencrypted in a separate step.

I'd like to add support for:
- creating a VM with an encrypted storage policy and attaching subresource disks with encrypted storage policies. 
- attaching already encrypted disks to a new VM with an encrypted storage policy

Would I be able to get support in doing this?

### Use Case(s)

We want to deploy VMs with encrypted disks.

### Potential Terraform Provider Configuration

_No response_

### References

#584 
https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-06E45092-22DD-4064-AF55-FB5D0FD4E588.html

### PR DESCRIPTION
**Pull request by belleatkins**
###Description
As per issue: (https://github.com/hashicorp/terraform-provider-vsphere/issues/1796)
This MR is to add Volume Encryption Support for deploying in VSphere.
It does this by running additional post-deployment steps to set the storage policy separately (to get around the fact that vSphere doesn't support setting the storage policy on disk attachment). It runs an additional step to revert the name change that occurs under foot.

A storage policy would be specified in the main.tf as follows:

```hcl
`resource "vsphere_virtual_machine" "belle-pcc_vms" {
  clone {
    template_uuid    = data.vsphere_virtual_machine.template.id
  }
  count              = 1
  scsi_type          = data.vsphere_virtual_machine.template.scsi_type
  datastore_id       = data.vsphere_datastore.datastore[count.index].id
  storage_policy_id  = data.vsphere_storage_policy.policy[count.index].id

  depends_on         = [local_file.user_data_json]
  disk {
    datastore_id        = data.vsphere_datastore.datastore[count.index].id
    label               = "disk0"
    keep_on_remove      = false
    size                = var.boot_disk_size
    thin_provisioned    = true
    storage_policy_id   = data.vsphere_storage_policy.policy[count.index].id
  }
  disk {
    datastore_id        = data.vsphere_datastore.datastore[count.index].id
    label               = "disk1"
    unit_number         = 1
    attach              = true
    path                = vsphere_virtual_disk.disk[count.index].vmdk_path
    storage_policy_id   = data.vsphere_storage_policy.policy[count.index].id
  }`
```

Use of this feature requires the correct VSphere Cryptography permissions.

Acceptance tests
 Have you added an acceptance test for the functionality being added?
 Have you run the acceptance tests on this branch?
[ ]
I have not run acceptance tests as my vsphere environment does not have access to any NAS storage, so I cannot set environment variable TF_VAR_VSPHERE_NAS_HOST or TF_VAR_VSPHERE_NFS_PATH, so tests are failing with 

```console
make testacc TESTARGS="-run=TestAccResourceVSphereVirtualMachine_basic"
Error: error mounting datastore: host "<TF_VAR_VSPHERE_ESXI2>": ServerFaultCode: A specified parameter was not correct:

  with vsphere_nas_datastore.ds1,
  on terraform_plugin_test.tf line 29, in resource "vsphere_nas_datastore" "ds1":
  29: resource "vsphere_nas_datastore" "ds1" {

```
I'd appreciate guidance on how to get around this, and which acceptance tests to run if it is possible.

Manual testing of this feature is complete. This feature is now used in our product.
Manual testing included test sessions under:
- performance 
- robustness and resiliency 
- deleting the VM and attaching a new VM to the existing encrypted disks
- deploying a VM with fresh encrypted disks
- One bug was found and fixed: datastores containing the encrypted disks were not successfully detected when inside a folder
- a light cross spectrum of storage policies were tried and tested

Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):
FEATURES:

virtual_machine_disk_subresource: Add support for deploying a VM with encrypted disks via specifying a storage policy which has encryption enabled. 
...

References

Closes #1796

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Marking as draft due to merge conflicts.

**Comment by tenthirtyam** [comment]
CI is failing.

```bash
==> Checking that code complies with gofmt requirements...
[5](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:6)
gofmt needs running on the following files:
[6](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:7)
make: *** [GNUmakefile:27: fmtcheck] Error 1
[7](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:8)
./vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
[8](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:9)
./vsphere/data_source_vsphere_host.go
[9](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:10)
You can use the command: `make fmt` to reformat code.
[10](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4447034308/jobs/7808976110#step:5:11)
Error: Process completed with exit code 2.
```

**Comment by belleatkins** [comment]
fixed CI

**Comment by tenthirtyam** [comment]
CI Failing 

```bash
==> Checking that code complies with gofmt requirements...
[5](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:6)
gofmt needs running on the following files:
[6](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:7)
./vsphere/internal/virtualdevice/virtual_machine_disk_subresource.go
[7](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:8)
make: *** [GNUmakefile:27: fmtcheck] Error 1
[8](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:9)
./vsphere/data_source_vsphere_host.go
[9](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:10)
You can use the command: `make fmt` to reformat code.
[10](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/4448677556/jobs/7812906362?pr=1839#step:5:11)
Error: Process completed with exit code 2.
```

**Comment by belleatkins** [comment]
make fmt no longer makes any formatting changes so I'm not sure why the UTs are failing with that error

**Comment by belleatkins** [comment]
fixed CI

**Comment by tenthirtyam** [comment]
CI Passing

**Comment by tenthirtyam** [comment]
Marked as draft as this needs an acceptance test and there are no updates on manual testing per OP.

**Comment by belleatkins** [comment]
> Marked as draft as this needs an acceptance test and there are no updates on manual testing per OP.

manual testing completed

**Comment by tenthirtyam** [comment]
Hi @belleatkins!  There are still merge conflicts for this one that need to be addressed.

Hi @martons-msw! You'll need to sign the HashiCorp CLA before this can be reviewed and merged.

**Comment by tenthirtyam** [comment]
Hi @belleatkins! There are still merge conflicts for this one that need to be addressed.

Hi @martons-msw! You'll need to sign the HashiCorp CLA before this can be reviewed and merged.

**Comment by DariusMR** [comment]
Hello, any news on this topic ?

**Comment by tenthirtyam** [comment]
Hi @martons-msw! You'll need to sign the HashiCorp CLA before this can be reviewed and merged.

**Comment by tenthirtyam** [comment]
There haven't been any updates.

- @belleatkins - there were still merge conflicts for this one that need to be addressed.

- @martons-msw! - the HashiCorp CLA needed to be signed.

I'm closing this pull request for now. Please feel free to create a new pull request if this feature is still desired.

**Pull request closed without merging**
