### PR TITLE
feature: instant_clone

### PR DESCRIPTION
**Pull request by Anant99-sys**
### Description
Implementation for instant clone functionality

- The Instant Clone technology is used to create powered-on virtual machines from the running state of another powered-on virtual machine.
- The result of an Instant Clone operation is a new virtual machine that is identical to the source virtual machine.
- With Instant Clone you can create new virtual machines from a controlled point in time.
Instant cloning is very convenient for large-scale application deployments because it ensures memory efficiency and allows for creating numerous virtual machines on a single host.
- This functionality can be used for Creating a powered-on Instant Clone of a virtual machine.

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccResourceVSphereVirtualMachine_Instantclone"

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVSphereVirtualMachine_Instantclone -timeout 240m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
=== RUN   TestAccResourceVSphereVirtualMachine_Instantclone
--- PASS: TestAccResourceVSphereVirtualMachine_Instantclone (188.07s)
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	191.274s
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/administrationroles	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/clustercomputeresource	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/computeresource	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/contentlibrary	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/customattribute	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datacenter	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datastore	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/dvportgroup	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/envbrowse	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/folder	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/hostsystem	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/network	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/nsx	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/provider	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/resourcepool	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/spbm	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/storagepod	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/structure	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/testhelper	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/utils	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vappcontainer	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/viapi	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualdisk	(cached) [no tests to run]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualmachine	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vsansystem	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/virtualdevice	(cached) [no tests to run]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/vmworkflow	[no test files]

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/CHANGELOG.md):

```
Capability to Add Instant Clone for a Parent VM.
```

### CODE REVIEW

**Comment by Anant99-sys** [comment]
I have signed the CLA and it's still showing pending @hashibot @hashicorp-cla

**Comment by Anant99-sys** [comment]
recheck

**Comment by Anant99-sys** [comment]
How much time would it take for the review process so that it can be merged?

**Comment by Anant99-sys** [comment]
How can we make this PR be merged? Who are the authorized users?

**Comment by Anant99-sys** [comment]
Can the authorized users please review this so that PR be merged?

**Comment by Anant99-sys** [comment]
Can the authorized users please review this so that PR be merged?

**Comment by markpeek** [comment]
@koikonom could you review and merge this change?

**Comment by markpeek** [comment]
@koikonom @aareet any timeframe to review and merge this change?

**Comment by redeux** [comment]
Thank you for your contribution to the vSphere provider. I've tagged this as a candidate for our next release. Please ensure that the all requirements, such as signing the Contributor License Agreement, are met. We will start planning for the next release soon, but will be unable to evaluate your PR until all requirements are met.

**Comment by Anant99-sys** [comment]
> Thank you for your contribution to the vSphere provider. I've tagged this as a candidate for our next release. Please ensure that the all requirements, such as signing the Contributor License Agreement, are met. We will start planning for the next release soon, but will be unable to evaluate your PR until all requirements are met.

I have signed the CLA but it is still not updating

**Comment by redeux** [comment]
> I have signed the CLA but it is still not updating

Please see the message from the hashicorp-cla bot above: https://github.com/hashicorp/terraform-provider-vsphere/pull/1371#issuecomment-803966516

**Comment by Anant99-sys** [comment]
Screenshot 2021-07-16 at 11 56 04 PM
Screenshot 2021-07-16 at 11 55 58 PM
As you can see its not updating that i had signed the CLA.
can you please help or help me rectify this?

**Comment by aareet** [comment]
@Anant99-sys if you look at your commit history, does the email address in the commit match the one you are providing to the CLA bot?

**Comment by mfilipiak-ccg** [comment]
Bumping, since this seems dead in the water over the CLA.

Would love to have this feature merged in. Should somebody resubmit the patch so they can accept the CLA. I'm willing to help however necessary.

**Comment by tenthirtyam** [comment]
@Anant99-sys - 

Given that this is blocked by the CLA issue, I suggest considering resubmitting the PR based on [your fork/branch](https://github.com/Anant99-sys/terraform-provider-vsphere/tree/instant_module) by recreating [the changes](https://github.com/hashicorp/terraform-provider-vsphere/pull/1371/files) and signing the commit?

Set your email on the feature branch based on the email [that's signed the CLA](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere) and attached to your GitHub account): 

```bash
git config user.email yourname@domain.com
```

Sign-off in the commit description:

```text
Signed-off-by: Anant Chopra <yourname@domain.com>
```

Then submit the new PR for review.

Another possibility may be to allow a maintainer or delegate another contributor to submit the enhancement if the CLA issue can not be resolved.

Ryan

**Comment by Anant99-sys** [comment]
> @Anant99-sys -
> 
> Given that this is blocked by the CLA issue, I suggest considering resubmitting the PR based on [your fork/branch](https://github.com/Anant99-sys/terraform-provider-vsphere/tree/instant_module) by recreating [the changes](https://github.com/hashicorp/terraform-provider-vsphere/pull/1371/files) and signing the commit?
> 
> Set your email on the feature branch based on the email [that's signed the CLA](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere) and attached to your GitHub account):
> 
> ```shell
> git config user.email yourname@domain.com
> ```
> 
> Sign-off in the commit description:
> 
> ```
> Signed-off-by: Anant Chopra <yourname@domain.com>
> ```
> 
> Then submit the new PR for review.
> 
> Another possibility may be to allow a maintainer or delegate another contributor to submit the enhancement if the CLA issue can not be resolved.
> 
> Ryan

Thanks, Ryan. I followed the steps and created the new PR for review. Please take a look at https://github.com/hashicorp/terraform-provider-vsphere/pull/1516 to help approve

**Comment by tenthirtyam** [comment]
I suggest closing this PR since it’s replaced by #1516.

Ryan

**Pull request closed without merging**
