### PR TITLE
Fix VMDK upload failure on ESXi host using `vspshere_file` resource.

### PR DESCRIPTION
**Pull request by sumitmaggo**
### Description

Fixes issues where `vsphere_file` resource fails to upload VMDK file to ESXi host datastore.

VMDK disk upload has been tested with Terraform 0.13 version on ESXi.

### Release Note

`vsphere_file` resource: Fix upload of VMDK  to datastore on ESXi host. [GH-1409]

### References

Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1296
Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1243

### CODE REVIEW

**Comment by sumitmaggo** [comment]
@bill-rich @koikonom @aareet @sumitAgrawal007 Can you guys please look into this PR and provide your comments? Thanks in advance.

**Comment by sumitmaggo** [comment]
@bill-rich @koikonom @aareet @sumitAgrawal007 Can anyone please review this PR? Its been pending for too long and we are blocked because of it and not able to pick the latest vsphere provider version for ESXi.

**Comment by sumitmaggo** [comment]
@bill-rich @koikonom Can you please help getting this PR reviewed and merged? We need to move to the latest version of vsphere provider and this issue is blocking that.

**Comment by sumitmaggo** [comment]
@redeux Can you please check and review if this fix can also be added as a candidate for next release? This is also needed in addition to https://github.com/hashicorp/terraform-provider-vsphere/pull/1408 PR changes to move to the latest version of vsphere provider for ESXi deployment. Thanks in advance.

**Comment by sumitmaggo** [comment]
@appilon Can you please review and merge this PR as well? This is also needed in addition to #1408 to allow launching VM on ESXi server.

**Comment by sumitmaggo** [comment]
Thanks @tenthirtyam, updated the description to link it with the issue.

**Comment by tenthirtyam** [comment]
Hi @sumitmaggo, 

i took some time to build the provider from [sumitmaggo:bugfix/upload_vmdk](https://github.com/sumitmaggo/terraform-provider-vsphere/tree/bugfix/upload_vmdk) and ran some user tests on a 1.27 vmdk and the same error was presented.

- Terraform v1.1.5
- Provider "local/vmware/vsphere v2.0.3"
- vSphere v7.0.3(c)

```console
❯ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding local/vmware/vsphere versions matching ">= 2.0.3"...
- Installing local/vmware/vsphere v2.0.3...
- Installed local/vmware/vsphere v2.0.3 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
❯ terraform apply  -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_file.upload will be created
  + resource "vsphere_file" "upload" {
      + create_directories = true
      + datacenter         = "m01-dc01"
      + datastore          = "local-ssd-01"
      + destination_file   = "gh-1409/ubuntu.vmdk"
      + id                 = (known after apply)
      + source_file        = "/Users/johnsonryan/Downloads/ubuntu.vmdk"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
vsphere_file.upload: Creating...
vsphere_file.upload: Still creating... [10s elapsed]
.... time travel.
vsphere_file.upload: Still creating... [9m50s elapsed]
╷
│ Error: error A specified parameter was not correct: fileType
│ 
│   with vsphere_file.upload,
│   on main.tf line 17, in resource "vsphere_file" "upload":
│   17: resource "vsphere_file" "upload" {
│ 
╵
```

I'll take a look at the code changes and run some more tests.

Ryan

cc @appilon

**Comment by tenthirtyam** [comment]
@sumitmaggo - I found the issue and will submit a fix to your branch soon.

**Review by appilon — APPROVED** [review]

**Comment by sumitmaggo** [comment]
Thanks @appilon and @tenthirtyam for the review and merge of this PR.
When can we expect the next vsphere plugin 2.0.3 release?

**Pull request merged**
