### PR TITLE
Dependencies: Bump Go to 1.18

### PR DESCRIPTION
**Pull request by appilon**
Bump Go and remove vendoring. Don't be alarmed by the massive file history change.

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Quick note: The README.md will also need to be updated to reflect 0.18.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by appilon** [comment]
@tenthirtyam Should be covered unless I missed something?

**Comment by tenthirtyam** [comment]
😎 🚀

**Review by sheneska — APPROVED** [review]
LGTM

**Pull request merged**
