### PR TITLE
Set `devices` parameter as optional for `vsphere_distributed_switch` resource

### PR DESCRIPTION
**Pull request by haroldddd**
### Description
Updates the structure of distributed_virtual_switch: setting `devices` argument from `required` to `optional`.
By default, vCenter does not force a distributed-virtual-switch to be bound to any devices. This was a requirement introduced by terraform-vsphere-provider.

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/CHANGELOG.md):

`resource/distributed_virtual_switch` - `devices` argument is now optional [GH-1468]

### References

Closes  https://github.com/hashicorp/terraform-provider-vsphere/issues/1290

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Ideally, the docs should be updated to reflect optional as part of the PR.

Ryan

**Comment by haroldddd** [comment]
You're right. I've just updated the documentation to stay consistent with the code.

**Comment by haroldddd** [comment]
Any news on that one ?

**Comment by tenthirtyam** [comment]
@appilon, this pull request makes sense to review to relax requirement by the provider that differs from the API and UI methods.

Ryan

**Comment by appilon** [comment]
Going from required --> optional should be okay from a breaking change perspective. The PR will need to be rebased still (which I can handle) but I would like to see the tests for this resource be ran:
```
➜ make testacc TESTARGS='-run=TestAccResourceVSphereDistributedVirtualSwitch_'
```
Unfortunately without a test environment at the moment but I should be able to get one back up hopefully soon. If someone does have an environment configured for running tests (you will need to set several environment variables) feel free to post the results.

**Comment by tenthirtyam** [comment]
@haroldddd Can you update the description summary to include "Closes #1290" to link the issue and pull request?

Thanks,
Ryan

**Comment by tenthirtyam** [comment]
@appilon - would you mind rebasing this one for me and I'll start to take a look into it.

Thanks!
Ryan

**Comment by appilon** [comment]
@tenthirtyam When we merge I will perform a squash and merge (commits get squashed to 1, the conflict was in an intermediary commit which won't exist after squash) so no need to rebase at all. Could you do a quick test where you create a `vsphere_distributed_switch` without any devices and ensures it creates and destroys with no error?

**Comment by tenthirtyam** [comment]
@appilon, certainly! Stay tuned.

**Review by appilon — APPROVED** [review]

**Pull request merged**
