### PR TITLE
Add VM Shutdown

### PR DESCRIPTION
**Pull request by aishwarya128**
### Description
This feature helps to shutdown/power off a running virtual machine in the environment. User can import the deployed virtual machines using terraform configuration file for the existing infra and he/she can pass this parameter and power off the state.

### Release Note
NONE

### References
Closes: #1394

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Closes: #1394

**Comment by aishwarya128** [comment]
> Hi @aishwarya128
> 
> You may want to add "Closes: #1394" to the description to link the issue and pull request.
> 
> Ryan

Thanks @tenthirtyam ,have updated the description.

**Comment by tenthirtyam** [comment]
I think it might be good to consider how to align this one with #1407 and the proposed computed value for `power_state` so that these are grouped (`power_`) and that they each support all three power states of `PoweredOn`, `PoweredOff`, and `Suspended` that would be seen via API/PowerCLI.

For example:
- power_state : the desired state/status
- power_status : the current status

@appilon - what do you think? It's the a similar precedent in other providers?

If so, I can work with the both @aishwarya128 and @sumitmaggo to align these changes.

Ryan

**Comment by appilon** [comment]
I will have to think about these issues more, but I don't think there should be 2 variables, I think if we want to add the ability to control the power state of the VM it would be 1 optional attribute, Terraform is designed to have state match upstream, if there is mismatch the user would be notified of the drift. IE if you change a hypothetical new attribute `power_state` to some value, terraform expects to apply that change and then immediately read that state back form upstream and have it match what was set. I'll try and look at this feature request further.

**Comment by tenthirtyam** [comment]
After reviewing this with a colleague today, we were very much thinking the same and have some thoughts on how it could be addressed.

**Comment by tenthirtyam** [comment]
HI @aishwarya128 👋🏻 

We appreciate your contribution. Unfortunately, after some deliberations with the maintainers, we've decided that at this time this capability will not be added to the provider as it tends to blur the lines between [mutable vs. immutable infrastructure](https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure).

If you take a look back to #327, the same enhancement was requested and the maintainer at the time [shared the reasoning](https://github.com/hashicorp/terraform-provider-vsphere/issues/327#issuecomment-352559036) at the time for not including the capability. 

We'd like to encourage you to help contribute to other issues (bugs or enhancements). You can look at the [upcoming version milestones](https://github.com/hashicorp/terraform-provider-vsphere/milestones) to see if there are any in which you'd like to assist.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Pull request closed without merging**
