### PR TITLE
feat: add support for vlcm (offline software depots, cluster images)

### LINKED ISSUE #2142: Add support for vLCM on compute clusters
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

The provider lacks the capability for host image management. This is a request to provide automation for cluster-level ESXi image management and the capacity to customize images by uploading additional components.

### Use Case(s)

I would like to be able to upload a custom driver to my vCenter server and apply it to all hosts in a compute cluster.
I would like to be able to update that driver simultaneously on all of my hosts when necessary.
I would like to be able to manage all of my hosts with a single ESXi image.

### Potential Terraform Provider Configuration

_No response_

### References

https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/depots.offline/
https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/depots.offline.content/
https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/depot_content.components/
https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/depot_content.base_images/
https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/clusters.enablement.software/
https://developer.vmware.com/apis/vsphere-automation/latest/esx/settings/clusters.configuration.drafts/

### PR DESCRIPTION
**Pull request by stoyanzhelyazkov**
### Description

The goal of this PR is to provide users with the ability to configure custom images for clusters using vLCM.
To achieve that I am adding
1. A new resource for offline software depots. Support for online depots can be added at a later time.
Only depots with source type "PULL" are supported. This is intentional and aims to discourage the use of the deprecated VUM functionality.
2. A new data source for base images. Declaring this data source allows users to retrieve the full list of available ESXi versions for their environment.
3. A new property for compute clusters that serves as an entry point for the vLCM configuration.
It allows users to select a base image and a list of custom components from a depot.
Configuring this property for the first time also enables vLCM on the cluster

### Acceptance tests
- [X] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

Output of [make test](https://github.com/hashicorp/terraform-provider-vsphere/files/14508798/test_out.txt)

Ran the following acceptance tests:

```console
=== RUN   TestAccResourceVSphereComputeCluster_basic
--- PASS: TestAccResourceVSphereComputeCluster_basic (133.60s)
=== RUN   TestAccResourceVSphereComputeCluster_haAdmissionControlPolicyDisabled
--- PASS: TestAccResourceVSphereComputeCluster_haAdmissionControlPolicyDisabled (169.08s)
=== RUN   TestAccResourceVSphereComputeCluster_drsHAEnabled
--- PASS: TestAccResourceVSphereComputeCluster_drsHAEnabled (127.58s)
=== RUN   TestAccResourceVSphereComputeCluster_vlcm
--- PASS: TestAccResourceVSphereComputeCluster_vlcm (766.70s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanDedupEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanDedupEnabled (167.37s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanCompressionEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanCompressionEnabled (151.22s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanPerfEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanPerfEnabled (152.49s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanPerfVerboseEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanPerfVerboseEnabled (147.17s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanPerfVerboseDiagnosticEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanPerfVerboseDiagnosticEnabled (146.63s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanUnmapEnabledwithVsanEnabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanUnmapEnabledwithVsanEnabled (147.46s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled (230.83s)
=== RUN   TestAccResourceVSphereComputeCluster_vsanDITEncryption
--- PASS: TestAccResourceVSphereComputeCluster_vsanDITEncryption (168.3)
=== RUN   TestAccResourceVSphereOfflineSoftwareDepot_basic
--- PASS: TestAccResourceVSphereOfflineSoftwareDepot_basic (168.36s)
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
Adding support for vLCM - a new resource for offline depots, a new data source for base images, new properties on clusters that allow users to do base image customizations
```
### References

Closes #2142

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Dependent on the next release of `vmware/govmomi` with https://github.com/vmware/govmomi/pull/3377.

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
Hi Stoyan 👋🏻 -

Could you add the required documenation to the `/website/docs/...` directories for the new resource and data source?

I'll get a PR in for updating `vmware/govmomi` to v0.36.0 that released today with your upstream changes and then rebase this PR.

Ryan

**Comment by stoyanzhelyazkov** [comment]
> Hi Stoyan 👋🏻 -
> 
> Could you add the required documenation to the `/website/docs/...` directories for the new resource and data source?
> 
> I'll get a PR in for updating `vmware/govmomi` to v0.36.0 that released today with your upstream changes and then rebase this PR.
> 
> Ryan

Thanks for taking care of the govmomi bump. I will add docs for the new entities

**Comment by tenthirtyam** [comment]
Rebased but the CI is failing:

```console
--- FAIL: TestProvider (0.00s)
    provider_test.go:25: err: resource vsphere_offline_software_depot: key: ValidateFunc is for validating user input, there's nothing to validate on computed-only field
FAIL
```

**Comment by stoyanzhelyazkov** [comment]
> Rebased but the CI is failing:
> 
> ```
> --- FAIL: TestProvider (0.00s)
>     provider_test.go:25: err: resource vsphere_offline_software_depot: key: ValidateFunc is for validating user input, there's nothing to validate on computed-only field
> FAIL
> ```

Silly me, I added validations on my computed properties

**Review by tenthirtyam — APPROVED** [review]
LGTM!

**Pull request merged**
