### PR TITLE
docs: fix grammatical errors

### PR DESCRIPTION
**Pull request by Attacktive**
### Description

Simple fixes on documentation plus a little bit of [reformatting](https://github.com/hashicorp/terraform-provider-vsphere/compare/main...Attacktive:terraform-provider-vsphere:main#diff-8b4bac5499caa6b488a8fa5cc57d0ef5da86e4843cd97fddeca129e2c6e03244R16-R18) which `gofmt` complained about.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccDataSourceVSphereHost'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccDataSourceVSphereHost -timeout 240m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
=== RUN   TestAccDataSourceVSphereHost_basic
    data_source_vsphere_host_test.go:63: set TF_VAR_VSPHERE_DATACENTER to run vsphere_host acceptance tests
--- SKIP: TestAccDataSourceVSphereHost_basic (2.35s)
=== RUN   TestAccDataSourceVSphereHost_defaultHost
    data_source_vsphere_host_test.go:63: set TF_VAR_VSPHERE_DATACENTER to run vsphere_host acceptance tests
--- SKIP: TestAccDataSourceVSphereHost_defaultHost (2.06s)
=== RUN   TestAccDataSourceVSphereHostThumbprint_basic
    data_source_vsphere_host_thumbprint_test.go:32: set TF_VAR_VSPHERE_ESXI1 to run vsphere_host_thumbprint acceptance tests
--- SKIP: TestAccDataSourceVSphereHostThumbprint_basic (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere 4.420s
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/administrationroles    [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/clustercomputeresource  [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/computeresource [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/contentlibrary  [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/customattribute [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datacenter      [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datastore       [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/dvportgroup     [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/envbrowse       [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/folder  [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/hostsystem      [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/network [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/nsx     [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy       [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/provider        [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/resourcepool    [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/spbm    [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/storagepod      [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/structure       [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/testhelper      [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/utils   [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vappcontainer   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/viapi   0.005s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualdisk     0.008s [no tests to run]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualmachine  [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vsanclient      [no test files]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vsansystem      [no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/virtualdevice  0.004s [no tests to run]
?       github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/vmworkflow     [no test files]
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
Documentation updates
```

### CODE REVIEW

**Review by tenthirtyam — COMMENTED** [review]
Thanks for the contribution, @Attacktive!

I notice that one CI is [not passing](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929) due to the reformat of `data_source_vsphere_host.go`

```console
==> Checking that code complies with gofmt requirements...
[5](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929#step:6:6)
gofmt needs running on the following files:
[6](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929#step:6:7)
make: *** [GNUmakefile:46: fmtcheck] Error 1
[7](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929#step:6:8)
./vsphere/data_source_vsphere_host.go
[8](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929#step:6:9)
You can use the command: `make fmt` to reformat code.
[9](https://github.com/hashicorp/terraform-provider-vsphere/actions/runs/3619520173/jobs/6102661929#step:6:10)
Error: Process completed with exit code 2.
```

As a general practice, it's also recommended to submit the pull request from an feature branch (e.g., `docs/fix-grammatical errors`).

**Review by tenthirtyam — COMMENTED** [review]
I suggest amending to exclude the reformat and we'll address this item seperately.

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
I suggest amending to exclude the reformat and we'll address this item seperately.

**Comment by Attacktive** [comment]
@tenthirtyam Whoops. I missed that error. 😅
Just reverted the last commit.
Thank you for your quick feedback.

**Review by tenthirtyam — APPROVED** [review]

**Pull request merged**
