### PR TITLE
#1190 - Add replacement trigger to virtual machine resource

### PR DESCRIPTION
**Pull request by fredrikhgrelland**
### Description

This PR implements a new key `replace_trigger` to `vsphere_virtual_machine`. This adresses feature request #1190 which proposes a way to force the replacement of a virtual machine resource. I am linking in this issue as it matches our needs.

Why?
Currently there is no way of forcing a replace of a virtual machine created with cloud_init. In order to force replacements of a cloned vm, you must change a clone customization parameter and this does not work (and does not make sense) when using cloud_init.

Working implementation: https://registry.terraform.io/providers/fredrikhgrelland/vsphere/latest/docs/resources/virtual_machine?pollNotifications=true#replace_trigger

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

I have not run acceptance tests using go tests, but have verified the functionality manually.
All we need to check is if changes to this key forces a replace, and it does as the schema specifically asks for it. 
This is core terraform functionality exposed.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/CHANGELOG.md):

```release-note
...
```

### CODE REVIEW

**Comment by fredrikhgrelland** [comment]
@koikonom Do you accept PRs? This is a fundamental need for phoenix-builds.

**Comment by redeux** [comment]
Hi @fredrikhgrelland.  Thank you for the PR.  

Terraform has a native capability to destroy and recreate a resource on the next apply using the [taint](https://www.terraform.io/docs/cli/commands/taint.html) command. Before we consider adding this kind of functionality to the vSphere provider, can you tell me whether you've tried to use taint and if so, why it doesn't work for you?  Thanks.

**Comment by fredrikhgrelland** [comment]
@redeux Thank you for coming back to me on this issue.

Yes, we are aware that you may taint a resource, but tainting should not be a necessary step in order to make changes to a resource. The problem here arise from the fact that any changes to cloud-init will never trigger a meaningful change in the vm. Currently this provider will write the cloud-init file, restart the vm and consider it to be changed.
Changing parameters in cloud-init, eg. network definitions/hostname etc., requires a replace of the resource in order to be effectuated.
The wanted behaviour mirrors that of the clone-stanza, that will replace a resource if you change networking parameters.

The use case here is that we want the resource to be _replaced_ when we need it to.
- Installations is done in packer and put into a template.
- Configurations are done in cloud-init while instantiating the template. Including introduction of secrets.

Changes to the template will replace the resource, as this is considered a change.
Changes to networking, renewal or changing secrets/roles etc. will not replace the resource, as this is not considered a change.

This patch will allow for phoenix-builds and immutable infrastructure on vsphere along with automated procedures.

Does this clarify the problem sufficiently?

**Comment by koikonom** [comment]
Hi @fredrikhgrelland 

Terraform 0.15.2 introduced a new `replace` parameter to plan and apply commands. Please take a look at https://www.terraform.io/docs/cli/commands/plan.html#replace-address, I think it will help in your case.

**Comment by fredrikhgrelland** [comment]
Thanks @koikonom for pointing this out. It will surely be easier for ad-hoc replacements along with -target, but unfortunately it does not meet our requirements. With this switch we must create custom wrapper scripts and it would _always_ replace the resources. This trigger is still needed in order to automate the replacement based on relevant changes, while keeping it in place when there is no need to replace it.

**Review by koikonom — APPROVED** [review]

**Pull request merged**
