### PR TITLE
fix: update to `datastore_id` applies to `r/virtual_machine` disk sub-resources

### LINKED ISSUE #1268: Updating the `datastore_id` on the `r/virtual_machine` does not apply to disk sub-resources
### Terraform Version
13.5

### vSphere Provider Version
1.24.2

### Affected Resource(s)
- `vsphere_virtual_machine`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 1.24.2"
    }
  }
}

provider "vsphere" {
  vsphere_server       = var.vcenter
  user                 = var.VSPHERE_USER
  password             = var.VSPHERE_PASSWORD
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.cluster
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_datastore" "manual" {
  name          = var.datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.network
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm1" {
  name                 = var.vmname
  resource_pool_id     = data.vsphere_compute_cluster.cluster.resource_pool_id 
  datastore_id = data.vsphere_datastore.manual.id
  num_cpus = 1
  memory   = 2048
  guest_id = "other3xLinux64Guest"
  wait_for_guest_net_timeout = 0

  network_interface {
    network_id   = data.vsphere_network.network.id
    adapter_type = "vmxnet3"
  }

  disk {
    label            = "disk0"
    size             = var.c_size
    eagerly_scrub    = false
    thin_provisioned = true
    unit_number      = 0
  }
}
```

### Debug Output
https://gist.github.com/jweigand/174beffb17846c1cee70b5c804f59db7
### Expected Behavior

`datastore_id` should be changed for both the global value on the VM resource, and the disk subresource, causing a storage migration for both the general VM files, the disk VMDK file. 

### Actual Behavior

`datastore_id` only changes for the global value, and only the general VM files are storage migrated. The disk subresource `datastore_id` value does not think it should change, and the disk VMDK files are left on the original datastore. 

```
  # vsphere_virtual_machine.vm1 will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm1" {
      ~ datastore_id                            = "datastore-1687" -> "datastore-82"
 
        disk {
            attach           = false
            controller_type  = "scsi"
            datastore_id     = "datastore-1687"
```
### Steps to Reproduce
1. `terraform apply` to create the VM
2. Change the value of `var.datastore` to the name of a different datastore.
3. `terraform plan` \ `terraform apply` to see that the disk subresource `datastore_id` value does not show it should change. 

### Important Factoids

This same issue happens when using SDRS datastore clusters, rather than individual datastores. 

On the initial VM creation, this is shown in the trace (edited for brevity):
```
2020/12/04 14:31:53 [WARN] Provider "registry.terraform.io/hashicorp/vsphere" produced an unexpected new value for vsphere_virtual_machine.vm1, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
	  - .disk[0].datastore_id: was cty.StringVal("<computed>"), but now cty.StringVal("datastore-1687")
```

### References

* #1125 (further down seems to show the same issue of the `datastore_id` value not changing for disks) 
* [Provider Documentation](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#virtual-machine-migration) specifically notes this should work: 
> Global datastore migration can be handled by changing the global datastore_id attribute. This triggers a storage migration for all disks that do not have an explicit datastore_id specified.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by dimitarproynov**
### Description

Fix updating the datastore_id on the r/virtual_machine does not apply to disk sub-resources

Added special handling for when default datastore changes (aka data.HasChange("datastore_id"), but the disk subresource shows no changes between old and new ResourceData.

Additionally added capability to run the provider in debug mode, by passing "--debug" parameter.
Fixed disk device matching while iterating over VM devices in post Acc test assertions to be done via UUID instead of DatastorePath.

Testing done:

`make build` - passed

Used the snippet provided in the bug to create a new vm.

**Before fix:** 

the issue reproduced: only the VM config files were relocated from "datastore1" to "datastore2", when changing the default datastore to "datastore2"
Acc test TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting does not pass.

**After fix:**

Changed default datastore from "datastore1" to "datastore2", observed both VM config files and disk being relocated to "datastore2"

Added a second disk to the VM, placed on "datastore2" (datastore_id=datastore2.id),
Changed default datastore from "datastore1" to "datastore2", changed "datastore_id" of second disk to "datastore1"
Observed VM config files and first disk being relocated from "datastore1" to "datastore2", while second disk being relocated from "datastore2" to "datastore1"

Acc tests `TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting` and `TestAccResourceVSphereVirtualMachine_storageVMotionSingleDisk` pass.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
make testacc TESTARGS="-run='TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting|TestAccResourceVSphereVirtualMachine_storageVMotionSingleDisk'"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run='TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting|TestAccResourceVSphereVirtualMachine_storageVMotionSingleDisk' -timeout 240m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
=== RUN   TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting
--- PASS: TestAccResourceVSphereVirtualMachine_storageVMotionGlobalSetting (290.30s)
=== RUN   TestAccResourceVSphereVirtualMachine_storageVMotionSingleDisk
--- PASS: TestAccResourceVSphereVirtualMachine_storageVMotionSingleDisk (386.07s)

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

Bugfix:

`r/virtual_machine`: Updating the `datastore_id` on `r/virtual_machine` will apply to disk sub-resources resolving issue [GH-1268](https://github.com/hashicorp/terraform-provider-vsphere/issues/1268). [GH-1817](https://github.com/hashicorp/terraform-provider-vsphere/pull/1817)

### References

Closes #1268

### CODE REVIEW

**Comment by tenthirtyam** [comment]
> **Note**
>
> Contributed by [Dimitar Proynov](https://github.com/dimitarproynov), vSphere Engineering at VMware.

**Review by tenthirtyam — APPROVED** [review]
Tested with POSITIVE results:

Configuration (Abbreviated):

```hcl
resource "vsphere_virtual_machine" "vm" {
  name                    = var.vm_name
  folder                  = var.vsphere_folder
  num_cpus                = var.vm_cpus
  memory                  = var.vm_memory
  firmware                = var.vm_firmware
  efi_secure_boot_enabled = var.vm_efi_secure_boot_enabled
  guest_id                = data.vsphere_virtual_machine.template.guest_id
  datastore_id            = data.vsphere_datastore.datastore.id
  resource_pool_id        = data.vsphere_resource_pool.pool.id
  network_interface {
    network_id = data.vsphere_network.network.id
  }
  disk {
    label            = "disk0"
    size             = data.vsphere_virtual_machine.template.disks[0].size
    eagerly_scrub    = data.vsphere_virtual_machine.template.disks[0].eagerly_scrub
    thin_provisioned = data.vsphere_virtual_machine.template.disks[0].thin_provisioned
  }
  disk {
    label            = "disk1"
    size             = 10
    eagerly_scrub    = false
    thin_provisioned = true
    unit_number      = 1
  }
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }
  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
  extra_config = {
    "guestinfo.metadata"          = base64encode(file("${path.module}/metadata.yml"))
    "guestinfo.metadata.encoding" = "base64"
    "guestinfo.userdata"          = base64encode(file("${path.module}/userdata.yml"))
    "guestinfo.userdata.encoding" = "base64"
  }
}
```

Tests:

```console
➜ terraform plan                
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_compute_cluster.cluster: Reading...
data.vsphere_network.network: Reading...
data.vsphere_datastore.datastore: Reading...
data.vsphere_virtual_machine.template: Reading...
data.vsphere_network.network: Read complete after 0s [id=network-1001]
data.vsphere_datastore.datastore: Read complete after 0s [id=datastore-52034]
data.vsphere_compute_cluster.cluster: Read complete after 0s [id=domain-c6045]
data.vsphere_resource_pool.pool: Reading...
data.vsphere_resource_pool.pool: Read complete after 0s [id=resgroup-6046]
data.vsphere_virtual_machine.template: Read complete after 0s [id=4202fdca-4c30-e1aa-97d4-a927e5a73db0]
vsphere_virtual_machine.vm: Refreshing state... [id=42029879-429b-04d6-50ce-5f45a77f5935]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      ~ datastore_id                            = "datastore-11" -> "datastore-52034"
        id                                      = "42029879-429b-04d6-50ce-5f45a77f5935"
        name                                    = "ubuntu-cloud-init"
        tags                                    = []
        # (69 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.

packer-examples-for-vsphere/terraform/vsphere-virtual-machine/template-linux-cloud-init on  v22.12-mac [✘!?] 
➜ terraform apply --auto-approve
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_datastore.datastore: Reading...
data.vsphere_compute_cluster.cluster: Reading...
data.vsphere_network.network: Reading...
data.vsphere_virtual_machine.template: Reading...
data.vsphere_datastore.datastore: Read complete after 0s [id=datastore-52034]
data.vsphere_network.network: Read complete after 0s [id=network-1001]
data.vsphere_compute_cluster.cluster: Read complete after 0s [id=domain-c6045]
data.vsphere_resource_pool.pool: Reading...
data.vsphere_resource_pool.pool: Read complete after 0s [id=resgroup-6046]
data.vsphere_virtual_machine.template: Read complete after 0s [id=4202fdca-4c30-e1aa-97d4-a927e5a73db0]
vsphere_virtual_machine.vm: Refreshing state... [id=42029879-429b-04d6-50ce-5f45a77f5935]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_virtual_machine.vm will be updated in-place
  ~ resource "vsphere_virtual_machine" "vm" {
      ~ datastore_id                            = "datastore-11" -> "datastore-52034"
        id                                      = "42029879-429b-04d6-50ce-5f45a77f5935"
        name                                    = "ubuntu-cloud-init"
        tags                                    = []
        # (69 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
vsphere_virtual_machine.vm: Modifying... [id=42029879-429b-04d6-50ce-5f45a77f5935]
vsphere_virtual_machine.vm: Modifications complete after 5s [id=42029879-429b-04d6-50ce-5f45a77f5935]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Terraform State is accurate:

(Abbreviated)
```hcl
            "datacenter_id": null,
            "datastore_cluster_id": null,
            "datastore_id": "datastore-52034",
            "default_ip_address": "172.16.11.192",
            "disk": [
              {
                "attach": false,
                "controller_type": "scsi",
                "datastore_id": "datastore-52034",
                "device_address": "scsi:0:0",
                "disk_mode": "persistent",
                "disk_sharing": "sharingNone",
                "eagerly_scrub": false,
                "io_limit": -1,
                "io_reservation": 0,
                "io_share_count": 1000,
                "io_share_level": "normal",
                "keep_on_remove": false,
                "key": 2000,
                "label": "disk0",
                "path": "ubuntu-cloud-init/ubuntu-cloud-init.vmdk",
                "size": 40,
                "storage_policy_id": "",
                "thin_provisioned": false,
                "unit_number": 0,
                "uuid": "6000C29d-a4c7-30de-8d66-7f3c78828276",
                "write_through": false
              },
              {
                "attach": false,
                "controller_type": "scsi",
                "datastore_id": "datastore-52034",
                "device_address": "scsi:0:1",
                "disk_mode": "persistent",
                "disk_sharing": "sharingNone",
                "eagerly_scrub": false,
                "io_limit": -1,
                "io_reservation": 0,
                "io_share_count": 1000,
                "io_share_level": "normal",
                "keep_on_remove": false,
                "key": 2001,
                "label": "disk1",
                "path": "ubuntu-cloud-init/ubuntu-cloud-init_1.vmdk",
                "size": 10,
                "storage_policy_id": "",
                "thin_provisioned": true,
                "unit_number": 1,
                "uuid": "6000C298-6caa-ca08-9249-128dc853a287",
                "write_through": false
              }
            ],
```

**Comment by appilon** [comment]
I'm just running through all the tests affected by `testAccResourceVSphereVirtualMachineCheckVmdkDatastore` being changed, checking for regressions, many of these tests I can't run to begin with in my setup.

**Review by appilon — APPROVED** [review]
LGTM, no regressions and a few more tests pass

**Pull request merged**
