### PR TITLE
fix: race condition configuring vSAN and vSAN services

### PR DESCRIPTION
**Pull request by SlimYang**
### Description

When we are enabling vSAN and the vSAN-related features, like dedupe/compression or vSAN performance service, there could be a race condition that these vSAN features cannot be properly enabled. On the vSphere task dashboard, we will see the task failed with the error message "The operation is not supported on the object".

The root cause of the above issue is that we can see the enabling vSAN operation and the enable vSAN feature operation are in two API calls to the backend, and they are not properly synchronized to avoid the race condition that when the vSAN features are being enabled, vSAN is already in a stable state of enabled.

This change fixes the above issue by setting up the proper API call sequence in the vSAN and HA enable/disable workflow to ensure that the enable state can be properly configured.

### Acceptance tests
- [X] Have you added an acceptance test for the functionality being added?
- [X] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

[worker@sc2-10-186-27-70 terraform-provider-vsphere-main]$ make testacc TESTARGS="-run=TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled -timeout 240m
?   	github.com/hashicorp/terraform-provider-vsphere	[no test files]
=== RUN   TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled
--- PASS: TestAccResourceVSphereComputeCluster_vsanUnmapDisabledwithVsanDisabled (256.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere	256.426s
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/administrationroles	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/clustercomputeresource	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/computeresource	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/contentlibrary	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/customattribute	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datacenter	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/datastore	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/dvportgroup	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/envbrowse	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/folder	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/hostsystem	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/network	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/nsx	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/ovfdeploy	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/provider	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/resourcepool	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/spbm	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/storagepod	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/structure	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/testhelper	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/utils	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vappcontainer	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/viapi	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualdisk	(cached) [no tests to run]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/virtualmachine	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vsanclient	[no test files]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/vsansystem	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/virtualdevice	(cached) [no tests to run]
?   	github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/vmworkflow	[no test files]
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):
```release-note
NONE.
```
### References

Closes https://github.com/hashicorp/terraform-provider-vsphere/issues/1738

### CODE REVIEW

**Comment by tenthirtyam** [comment]
Hi @SlimYang - I'll review this pull request next week and report back. 

Thanks for the continued contributions from you and the vSAN team.

**Review by tenthirtyam — DISMISSED** [review]
Worked perfectly enabling vSAN and each of the configurable services. 🚀 

```hcl
resource "vsphere_compute_cluster" "vsan-cluster0" {
  name                                 = "vsan-cluster0"
  datacenter_id                        = data.vsphere_datacenter.datacenter.id
  host_system_ids                      = data.vsphere_host.hosts0.*.id
  drs_enabled                          = false
  ha_enabled                           = true
  vsan_enabled                         = true
  vsan_dedup_enabled                   = true
  vsan_compression_enabled             = true
  vsan_performance_enabled             = true
  vsan_network_diagnostic_mode_enabled = true
  vsan_verbose_mode_enabled            = true
}

resource "vsphere_compute_cluster" "vsan-cluster1" {
  name                                 = "vsan-cluster1"
  datacenter_id                        = data.vsphere_datacenter.datacenter.id
  host_system_ids                      = data.vsphere_host.hosts1.*.id
  drs_enabled                          = false
  ha_enabled                           = true
  vsan_enabled                         = true
  vsan_dedup_enabled                   = true
  vsan_compression_enabled             = true
  vsan_performance_enabled             = true
  vsan_network_diagnostic_mode_enabled = true
  vsan_verbose_mode_enabled            = true
}
```

```bash
Downloads/vsan/cluster took 4.1s 
➜ terraform apply --auto-approve
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_host.hosts1[1]: Reading...
data.vsphere_host.hosts0[2]: Reading...
data.vsphere_host.hosts0[1]: Reading...
data.vsphere_host.hosts1[0]: Reading...
data.vsphere_host.hosts0[0]: Reading...
data.vsphere_host.hosts1[2]: Reading...
data.vsphere_host.hosts0[2]: Read complete after 2s [id=host-15]
data.vsphere_host.hosts1[1]: Read complete after 2s [id=host-10]
data.vsphere_host.hosts0[1]: Read complete after 2s [id=host-16]
data.vsphere_host.hosts0[0]: Read complete after 2s [id=host-12]
data.vsphere_host.hosts1[2]: Read complete after 2s [id=host-13]
data.vsphere_host.hosts1[0]: Read complete after 2s [id=host-9]

Terraform used the selected providers to generate the following execution plan. Resource
actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_compute_cluster.vsan-cluster0 will be created
  + resource "vsphere_compute_cluster" "vsan-cluster0" {
      + datacenter_id                                         = "datacenter-3"
      + dpm_automation_level                                  = "manual"
      + dpm_enabled                                           = false
      + dpm_threshold                                         = 3
      + drs_automation_level                                  = "manual"
      + drs_enable_vm_overrides                               = true
      + drs_enabled                                           = false
      + drs_migration_threshold                               = 3
      + drs_scale_descendants_shares                          = "disabled"
      + ha_admission_control_host_failure_tolerance           = 1
      + ha_admission_control_performance_tolerance            = 100
      + ha_admission_control_policy                           = "resourcePercentage"
      + ha_admission_control_resource_percentage_auto_compute = true
      + ha_admission_control_resource_percentage_cpu          = 100
      + ha_admission_control_resource_percentage_memory       = 100
      + ha_admission_control_slot_policy_explicit_cpu         = 32
      + ha_admission_control_slot_policy_explicit_memory      = 100
      + ha_datastore_apd_recovery_action                      = "none"
      + ha_datastore_apd_response                             = "disabled"
      + ha_datastore_apd_response_delay                       = 180
      + ha_datastore_pdl_response                             = "disabled"
      + ha_enabled                                            = false
      + ha_heartbeat_datastore_policy                         = "allFeasibleDsWithUserPreference"
      + ha_host_isolation_response                            = "none"
      + ha_host_monitoring                                    = "enabled"
      + ha_vm_component_protection                            = "enabled"
      + ha_vm_dependency_restart_condition                    = "none"
      + ha_vm_failure_interval                                = 30
      + ha_vm_maximum_failure_window                          = -1
      + ha_vm_maximum_resets                                  = 3
      + ha_vm_minimum_uptime                                  = 120
      + ha_vm_monitoring                                      = "vmMonitoringDisabled"
      + ha_vm_restart_priority                                = "medium"
      + ha_vm_restart_timeout                                 = 600
      + host_cluster_exit_timeout                             = 3600
      + host_system_ids                                       = [
          + "host-12",
          + "host-15",
          + "host-16",
        ]
      + id                                                    = (known after apply)
      + name                                                  = "vsan-cluster0"
      + proactive_ha_automation_level                         = "Manual"
      + proactive_ha_moderate_remediation                     = "QuarantineMode"
      + proactive_ha_severe_remediation                       = "QuarantineMode"
      + resource_pool_id                                      = (known after apply)
      + vsan_compression_enabled                              = true
      + vsan_dedup_enabled                                    = true
      + vsan_enabled                                          = true
      + vsan_network_diagnostic_mode_enabled                  = true
      + vsan_performance_enabled                              = true
      + vsan_unmap_enabled                                    = (known after apply)
      + vsan_verbose_mode_enabled                             = true

      + vsan_disk_group {
          + cache   = (known after apply)
          + storage = (known after apply)
        }
    }

  # vsphere_compute_cluster.vsan-cluster1 will be created
  + resource "vsphere_compute_cluster" "vsan-cluster1" {
      + datacenter_id                                         = "datacenter-3"
      + dpm_automation_level                                  = "manual"
      + dpm_enabled                                           = false
      + dpm_threshold                                         = 3
      + drs_automation_level                                  = "manual"
      + drs_enable_vm_overrides                               = true
      + drs_enabled                                           = false
      + drs_migration_threshold                               = 3
      + drs_scale_descendants_shares                          = "disabled"
      + ha_admission_control_host_failure_tolerance           = 1
      + ha_admission_control_performance_tolerance            = 100
      + ha_admission_control_policy                           = "resourcePercentage"
      + ha_admission_control_resource_percentage_auto_compute = true
      + ha_admission_control_resource_percentage_cpu          = 100
      + ha_admission_control_resource_percentage_memory       = 100
      + ha_admission_control_slot_policy_explicit_cpu         = 32
      + ha_admission_control_slot_policy_explicit_memory      = 100
      + ha_datastore_apd_recovery_action                      = "none"
      + ha_datastore_apd_response                             = "disabled"
      + ha_datastore_apd_response_delay                       = 180
      + ha_datastore_pdl_response                             = "disabled"
      + ha_enabled                                            = false
      + ha_heartbeat_datastore_policy                         = "allFeasibleDsWithUserPreference"
      + ha_host_isolation_response                            = "none"
      + ha_host_monitoring                                    = "enabled"
      + ha_vm_component_protection                            = "enabled"
      + ha_vm_dependency_restart_condition                    = "none"
      + ha_vm_failure_interval                                = 30
      + ha_vm_maximum_failure_window                          = -1
      + ha_vm_maximum_resets                                  = 3
      + ha_vm_minimum_uptime                                  = 120
      + ha_vm_monitoring                                      = "vmMonitoringDisabled"
      + ha_vm_restart_priority                                = "medium"
      + ha_vm_restart_timeout                                 = 600
      + host_cluster_exit_timeout                             = 3600
      + host_system_ids                                       = [
          + "host-10",
          + "host-13",
          + "host-9",
        ]
      + id                                                    = (known after apply)
      + name                                                  = "vsan-cluster1"
      + proactive_ha_automation_level                         = "Manual"
      + proactive_ha_moderate_remediation                     = "QuarantineMode"
      + proactive_ha_severe_remediation                       = "QuarantineMode"
      + resource_pool_id                                      = (known after apply)
      + vsan_compression_enabled                              = true
      + vsan_dedup_enabled                                    = true
      + vsan_enabled                                          = true
      + vsan_network_diagnostic_mode_enabled                  = true
      + vsan_performance_enabled                              = true
      + vsan_unmap_enabled                                    = (known after apply)
      + vsan_verbose_mode_enabled                             = true

      + vsan_disk_group {
          + cache   = (known after apply)
          + storage = (known after apply)
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
vsphere_compute_cluster.vsan-cluster0: Creating...
vsphere_compute_cluster.vsan-cluster1: Creating...
vsphere_compute_cluster.vsan-cluster0: Still creating... [10s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [10s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [20s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [20s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [30s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [30s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [40s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [40s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [50s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [50s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m0s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m0s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m10s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m10s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m20s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m20s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m30s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m30s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m40s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m40s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [1m50s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [1m50s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still creating... [2m0s elapsed]
vsphere_compute_cluster.vsan-cluster1: Still creating... [2m0s elapsed]
vsphere_compute_cluster.vsan-cluster0: Creation complete after 2m2s [id=domain-c28]
vsphere_compute_cluster.vsan-cluster1: Still creating... [2m10s elapsed]
vsphere_compute_cluster.vsan-cluster1: Creation complete after 2m16s [id=domain-c29]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```

Subsequently, enabling both DRS and HA had no issue.

**Review by tenthirtyam — COMMENTED** [review]
I did a little more testing to remove vSphere HA from the cluster after having enabled it previously and then following-up with reenabling it. In both instances, it resulted in a plugin crash.

```console
Downloads/vsan/cluster took 6.4s 
➜ terraform apply --auto-approve
data.vsphere_datacenter.datacenter: Reading...
data.vsphere_datacenter.datacenter: Read complete after 0s [id=datacenter-3]
data.vsphere_host.hosts0[1]: Reading...
data.vsphere_host.hosts1[0]: Reading...
data.vsphere_host.hosts1[2]: Reading...
data.vsphere_host.hosts1[1]: Reading...
data.vsphere_host.hosts0[2]: Reading...
data.vsphere_host.hosts0[0]: Reading...
data.vsphere_host.hosts0[2]: Read complete after 2s [id=host-15]
data.vsphere_host.hosts1[1]: Read complete after 2s [id=host-10]
data.vsphere_host.hosts1[0]: Read complete after 2s [id=host-9]
data.vsphere_host.hosts0[1]: Read complete after 2s [id=host-16]
data.vsphere_host.hosts0[0]: Read complete after 2s [id=host-12]
vsphere_compute_cluster.vsan-cluster0: Refreshing state... [id=domain-c28]
data.vsphere_host.hosts1[2]: Read complete after 2s [id=host-13]
vsphere_compute_cluster.vsan-cluster1: Refreshing state... [id=domain-c29]

Terraform used the selected providers to generate the following execution plan. Resource
actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # vsphere_compute_cluster.vsan-cluster0 will be updated in-place
  ~ resource "vsphere_compute_cluster" "vsan-cluster0" {
      ~ ha_enabled                                            = false -> true
        id                                                    = "domain-c28"
        name                                                  = "vsan-cluster0"
        tags                                                  = []
        # (53 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

  # vsphere_compute_cluster.vsan-cluster1 will be updated in-place
  ~ resource "vsphere_compute_cluster" "vsan-cluster1" {
      ~ ha_enabled                                            = false -> true
        id                                                    = "domain-c29"
        name                                                  = "vsan-cluster1"
        tags                                                  = []
        # (53 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.
vsphere_compute_cluster.vsan-cluster1: Modifying... [id=domain-c29]
vsphere_compute_cluster.vsan-cluster0: Modifying... [id=domain-c28]
vsphere_compute_cluster.vsan-cluster1: Still modifying... [id=domain-c29, 10s elapsed]
vsphere_compute_cluster.vsan-cluster0: Still modifying... [id=domain-c28, 10s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with vsphere_compute_cluster.vsan-cluster0,
│   on main.tf line 72, in resource "vsphere_compute_cluster" "vsan-cluster0":
│   72: resource "vsphere_compute_cluster" "vsan-cluster0" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with vsphere_compute_cluster.vsan-cluster1,
│   on main.tf line 86, in resource "vsphere_compute_cluster" "vsan-cluster1":
│   86: resource "vsphere_compute_cluster" "vsan-cluster1" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-vsphere_v2.3.0 plugin:

panic: runtime error: slice bounds out of range [:1] with capacity 0

goroutine 116 [running]:
github.com/hashicorp/terraform-provider-vsphere/vsphere/internal/helper/structure.DropSliceItem(...)
        /Users/johnsonryan/Downloads/terraform-provider-vsphere-topic-ha-vsan-fix/vsphere/internal/helper/structure/structure_helper.go:569
github.com/hashicorp/terraform-provider-vsphere/vsphere.updateVsanDisks(0x21b8a20?, 0x1cdada0?, {0x1cdada0?, 0xc000387c20?})
        /Users/johnsonryan/Downloads/terraform-provider-vsphere-topic-ha-vsan-fix/vsphere/resource_vsphere_compute_cluster.go:1428 +0x149c
github.com/hashicorp/terraform-provider-vsphere/vsphere.resourceVSphereComputeClusterUpdate(0x0?, {0x1cdada0, 0xc000387c20})
        /Users/johnsonryan/Downloads/terraform-provider-vsphere-topic-ha-vsan-fix/vsphere/resource_vsphere_compute_cluster.go:662 +0x192
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x21c1dd0?, {0x21c1dd0?, 0xc000a007b0?}, 0xd?, {0x1cdada0?, 0xc000387c20?})
        /Users/johnsonryan/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:729 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002488c0, {0x21c1dd0, 0xc000a007b0}, 0xc0002bc820, 0xc0006ad600, {0x1cdada0, 0xc000387c20})
        /Users/johnsonryan/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/resource.go:847 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000cf980, {0x21c1d28?, 0xc00074ecc0?}, 0xc000981810)
        /Users/johnsonryan/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.17.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0003e03c0, {0x21c1dd0?, 0xc0007e1b00?}, 0xc000734380)
        /Users/johnsonryan/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1f65ac0?, 0xc0003e03c0}, {0x21c1dd0, 0xc0007e1b00}, 0xc00010e480, 0x0)
        /Users/johnsonryan/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.9.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022e700, {0x21c5998, 0xc000102d00}, 0xc00091f8c0, 0xc000111440, 0x2ae6800, 0x0)
        /Users/johnsonryan/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1283 +0xcfe
google.golang.org/grpc.(*Server).handleStream(0xc00022e700, {0x21c5998, 0xc000102d00}, 0xc00091f8c0, 0x0)
        /Users/johnsonryan/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:1620 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /Users/johnsonryan/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/johnsonryan/go/pkg/mod/google.golang.org/grpc@v1.46.0/server.go:920 +0x28a

Error: The terraform-provider-vsphere_v2.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Reapplying the plan worked however.

**Comment by tenthirtyam** [comment]
I’ll retest tomorrow with the current `v2.2.0` version but without the new vSAN features to see if the same issue is present in the latest GA version of the provider.

**Review by tenthirtyam — APPROVED** [review]
**Update**: 

I've tested the same with v2.2.0 (without the vSAN service features) and the same issue appears. The issue does not seem to be related to your changes and we'll track that under a separate issue. The workaround it to reapply - no changes will be seen as already applied.

Approving this pull request.

**Comment by appilon** [comment]
This was not a test I could run on our metal setup so taking @tenthirtyam's and OP's results

**Comment by tenthirtyam** [comment]
Worked vert well in our internal testing infra.

**Pull request merged**
